=== dotnet/runtime/src/coreclr/tools/aot/ILLink.Shared/ILLink.LinkAttributes.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema attributeFormDefault="unqualified"
		elementFormDefault="unqualified"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:complexType name="membertype">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element name="attribute" type="attribute" />
		</xsd:choice>
		<xsd:attribute name="feature" />
		<xsd:attribute name="featurevalue" type="xsd:boolean" />
		<xsd:attribute name="featuredefault" type="xsd:boolean" />
		<xsd:attribute name="name" />
		<xsd:attribute name="signature" />
	</xsd:complexType>

	<xsd:complexType name="method">
		<xsd:complexContent>
			<xsd:extension base="membertype">
				<xsd:choice maxOccurs="unbounded" minOccurs="0">
					<xsd:choice maxOccurs="unbounded" minOccurs="0">
						<xsd:element name="parameter">
							<xsd:complexType>
								<xsd:choice maxOccurs="unbounded" minOccurs="0">
									<xsd:element name="attribute" type="attribute" />
								</xsd:choice>
								<xsd:attribute name="name" use="required" />
							</xsd:complexType>
						</xsd:element>
					</xsd:choice>
					<xsd:choice maxOccurs="1" minOccurs="0">
						<xsd:element name="return">
							<xsd:complexType>
								<xsd:choice maxOccurs="unbounded" minOccurs="0">
									<xsd:element name="attribute" type="attribute" />
								</xsd:choice>
							</xsd:complexType>
						</xsd:element>
					</xsd:choice>
				</xsd:choice>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="argument" mixed="true">
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="argument" type="argument" />
		</xsd:choice>
		<xsd:attribute name="type" />
	</xsd:complexType>

	<xsd:complexType name="attribute">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element name="argument" type="argument" />
			<xsd:element name="property">
				<xsd:complexType mixed="true">
					<xsd:attribute name="name" use="required" />
				</xsd:complexType>
			</xsd:element>
		</xsd:choice>
		<xsd:attribute name="internal" />
		<xsd:attribute name="fullname" />
		<xsd:attribute name="assembly" />
	</xsd:complexType>

	<xsd:complexType name="assembly">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element name="attribute" type="attribute" />
			<xsd:element name="type" type="type" />
		</xsd:choice>
		<xsd:attribute name="fullname" use="required" />
		<xsd:attribute name="feature" />
		<xsd:attribute name="featurevalue" type="xsd:boolean" />
		<xsd:attribute name="featuredefault" type="xsd:boolean" />
	</xsd:complexType>

	<xsd:complexType name ="nestedtype">
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="event" type="membertype" />
			<xsd:element name="method" type="method" />
			<xsd:element name="field" type="membertype" />
			<xsd:element name="property" type="membertype" />
			<xsd:element name="attribute" type="attribute" />
			<xsd:element name="type" type="nestedtype" />
		</xsd:choice>
		<xsd:attribute name="name" use="required"/>
		<xsd:attribute name="feature" />
		<xsd:attribute name="featurevalue" type="xsd:boolean" />
		<xsd:attribute name="featuredefault" type="xsd:boolean" />
	</xsd:complexType>

	<xsd:complexType name="type">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element name="attribute" type="attribute" />
			<xsd:element name="event" type="membertype" />
			<xsd:element name="method" type="method" />
			<xsd:element name="field" type="membertype" />
			<xsd:element name="property" type="membertype" />
			<xsd:element name="type" type="nestedtype"/>
		</xsd:choice>
		<xsd:attribute name="feature" />
		<xsd:attribute name="featurevalue" type="xsd:boolean" />
		<xsd:attribute name="featuredefault" type="xsd:boolean" />
		<xsd:attribute name="fullname" use="required"/>
	</xsd:complexType>

	<xsd:element name="linker">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded" minOccurs="0">
				<xsd:element name="assembly" type="assembly" />
				<xsd:element name="type" type="type" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== dotnet/runtime/src/tools/illink/test/Mono.Linker.Tests.Cases/LinkAttributes/LinkAttributeErrorCases.xml
<?xml version="1.0" encoding="utf-8" ?>
<linker xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../src/ILLink.Shared/ILLink.LinkAttributes.xsd">
  <assembly fullname="test, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null">
    <type fullname="Mono.Linker.Tests.Cases.LinkAttributes.LinkAttributeErrorCases">
      <!-- IL2030 -->
      <attribute fullname="AttributeTypeName" assembly="NonExistentAssembly1"/>
      <attribute fullname="AttributeTypeName" assembly="MalformedAssemblyName, thisiswrong"/>
      
      <!-- IL2031 -->
      <attribute fullname="NonExistentAttribute"/>

      <!-- IL2022 -->
      <attribute fullname="Mono.Linker.Tests.Cases.LinkAttributes.LinkAttributeErrorCases/AttributeWithNoParametersAttribute">
        <argument>ExtraArgumentValue</argument>
      </attribute>

      <!-- IL2022 -->
      <attribute fullname="Mono.Linker.Tests.Cases.LinkAttributes.LinkAttributeErrorCases/AttributeWithEnumParameterAttribute">
        <argument>NonExistentEnumValue</argument>
      </attribute>

      <!-- IL2022 -->
      <attribute fullname="Mono.Linker.Tests.Cases.LinkAttributes.LinkAttributeErrorCases/AttributeWithIntParameterAttribute">
        <argument>NotANumber</argument>
      </attribute>

      <!-- IL2051 -->
      <attribute fullname="Mono.Linker.Tests.Cases.LinkAttributes.LinkAttributeErrorCases/AttributeWithPropertyAttribute">
        <property>StringValue</property>
      </attribute>

      <!-- IL2052 -->
      <attribute fullname="Mono.Linker.Tests.Cases.LinkAttributes.LinkAttributeErrorCases/AttributeWithPropertyAttribute">
        <property name="NonExistentPropertyName">StringValue</property>
      </attribute>

      <!-- IL2052 -->
      <attribute fullname="Mono.Linker.Tests.Cases.LinkAttributes.LinkAttributeErrorCases/AttributeWithPropertyAttribute">
        <property name="IntProperty">StringValue</property>
      </attribute>

      <!-- IL2023 -->
      <method name="GetTypeMethod">
        <return>
          <attribute fullname="Mono.Linker.Tests.Cases.LinkAttributes.LinkAttributeErrorCases/FirstAttribute" />
        </return>
        <return>
          <attribute fullname="Mono.Linker.Tests.Cases.LinkAttributes.LinkAttributeErrorCases/SecondAttribute" />
        </return>
      </method>

      <!-- IL2024 -->
      <method name="MethodWithParameter">
        <parameter name="methodParameter">
          <attribute fullname="Mono.Linker.Tests.Cases.LinkAttributes.LinkAttributeErrorCases/FirstAttribute" />
        </parameter>
        <parameter name="methodParameter">
          <attribute fullname="Mono.Linker.Tests.Cases.LinkAttributes.LinkAttributeErrorCases/SecondAttribute" />
        </parameter>
      </method>
    </type>

    <!-- IL2029 -->
    <attribute/>
    <attribute fullname=""/>
  </assembly>
  <assembly fullname="NonExistentAssembly2" />
</linker>

=== dotnet/runtime/src/tools/illink/test/Mono.Linker.Tests.Cases/LinkAttributes/LinkerAttributeRemovalConditional.xml
<?xml version="1.0" encoding="utf-8" ?>
<linker  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../src/ILLink.Shared/ILLink.LinkAttributes.xsd">
  <assembly fullname="test">
    <type fullname="Mono.Linker.Tests.Cases.LinkAttributes.TestConditionalRemoveAttribute">
      <attribute internal="RemoveAttributeInstances">
        <argument type="System.Object">
          <argument>remove1</argument>
        </argument>
      </attribute>
    </type>
    <type fullname="Mono.Linker.Tests.Cases.LinkAttributes.TestConditionalRemoveAttribute">
      <attribute internal="RemoveAttributeInstances">
        <argument type="System.Object">
          <argument type="System.Int32">100</argument>
        </argument>
      </attribute>
    </type>
    <type fullname="Mono.Linker.Tests.Cases.LinkAttributes.TestConditionalRemoveAttribute">
      <attribute internal="RemoveAttributeInstances">
        <argument type="System.Object">
          <argument>remove0</argument>
        </argument>
      </attribute>
      <attribute internal="RemoveAttributeInstances">
        <argument type="System.Object[]">
          <argument type="System.String">remove2</argument>
          <argument type="System.String">remove3</argument>
        </argument>
      </attribute>
      <attribute internal="RemoveAttributeInstances">
        <argument type="System.Object[]">
          <argument type="System.Object">
            <argument type="System.Int64">99</argument>
          </argument>
          <argument type="System.Object">
            <argument type="System.String">remove3</argument>
          </argument>
        </argument>
      </attribute>
    </type>
    <type fullname="Mono.Linker.Tests.Cases.LinkAttributes.TestConditionalRemoveAttribute">
        <attribute internal="RemoveAttributeInstances">
            <argument type="System.Object[]">
                <argument type="System.Object">
                    <argument type="System.Int32">72</argument>
                </argument>
                <argument type="System.Object">
                    <argument type="System.String[]">
                        <argument type="System.String">a</argument>
                        <argument type="System.String">b</argument>
                        <argument type="System.String">c</argument>
                        <argument type="System.String">d</argument>
                        <argument type="System.String">e</argument>
                    </argument>
                </argument>
            </argument>
        </attribute>
		<attribute internal="RemoveAttributeInstances">
			<argument type="System.Object">
				<argument type="System.Int32[]">
					<argument type="System.Int32">1</argument>
					<argument type="System.Int32">2</argument>
					<argument type="System.Int32">3</argument>
				</argument>
			</argument>
		</attribute>
    </type>
  </assembly>
</linker>
